export const COOKIE_REFRESH_TOKEN_KEY = "NEXT_BP_REFRESH_TOKEN";
export const COOKIE_ACCESS_TOKEN_KEY = "NEXT_BP_ACCESS_TOKEN";
export const COOKIE_LCOALE_KEY = "NEXT_BP_LOCALE";
export const COOKIE_ACCESS_TOKEN_ENCRYPTED_KEY =
  "NEXT_BP_ACCESS_TOKEN_ENCRYPTED";
export const COOKIE_EXPIRATION_TIME = 365;
